package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class DiscountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.title
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.comment
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.factory_metchat_map_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Integer factoryMetchatMapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.goods_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.goods_number
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Integer goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.amount
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.start_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Date startAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.end_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.create_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.update_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.confirm_status
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Byte confirmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.confirm_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Date confirmAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.confirm_by
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Integer confirmBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_info.valid
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.id
     *
     * @return the value of discount_info.id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.id
     *
     * @param id the value for discount_info.id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.title
     *
     * @return the value of discount_info.title
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.title
     *
     * @param title the value for discount_info.title
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.comment
     *
     * @return the value of discount_info.comment
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.comment
     *
     * @param comment the value for discount_info.comment
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.factory_metchat_map_id
     *
     * @return the value of discount_info.factory_metchat_map_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Integer getFactoryMetchatMapId() {
        return factoryMetchatMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.factory_metchat_map_id
     *
     * @param factoryMetchatMapId the value for discount_info.factory_metchat_map_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setFactoryMetchatMapId(Integer factoryMetchatMapId) {
        this.factoryMetchatMapId = factoryMetchatMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.goods_id
     *
     * @return the value of discount_info.goods_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.goods_id
     *
     * @param goodsId the value for discount_info.goods_id
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.goods_number
     *
     * @return the value of discount_info.goods_number
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.goods_number
     *
     * @param goodsNumber the value for discount_info.goods_number
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.amount
     *
     * @return the value of discount_info.amount
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.amount
     *
     * @param amount the value for discount_info.amount
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.start_at
     *
     * @return the value of discount_info.start_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.start_at
     *
     * @param startAt the value for discount_info.start_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.end_at
     *
     * @return the value of discount_info.end_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.end_at
     *
     * @param endAt the value for discount_info.end_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.create_at
     *
     * @return the value of discount_info.create_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.create_at
     *
     * @param createAt the value for discount_info.create_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.update_at
     *
     * @return the value of discount_info.update_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.update_at
     *
     * @param updateAt the value for discount_info.update_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.confirm_status
     *
     * @return the value of discount_info.confirm_status
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Byte getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.confirm_status
     *
     * @param confirmStatus the value for discount_info.confirm_status
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setConfirmStatus(Byte confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.confirm_at
     *
     * @return the value of discount_info.confirm_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Date getConfirmAt() {
        return confirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.confirm_at
     *
     * @param confirmAt the value for discount_info.confirm_at
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setConfirmAt(Date confirmAt) {
        this.confirmAt = confirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.confirm_by
     *
     * @return the value of discount_info.confirm_by
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Integer getConfirmBy() {
        return confirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.confirm_by
     *
     * @param confirmBy the value for discount_info.confirm_by
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setConfirmBy(Integer confirmBy) {
        this.confirmBy = confirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_info.valid
     *
     * @return the value of discount_info.valid
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_info.valid
     *
     * @param valid the value for discount_info.valid
     *
     * @mbg.generated Wed Mar 20 21:29:21 CST 2019
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}