package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class FactoryMerchantMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.factory_id
     *
     * @mbg.generated
     */
    private Integer factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.goods_number
     *
     * @mbg.generated
     */
    private Integer goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.trader_number
     *
     * @mbg.generated
     */
    private Integer traderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.discount_number
     *
     * @mbg.generated
     */
    private Integer discountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.campaign_number
     *
     * @mbg.generated
     */
    private Integer campaignNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.start_at
     *
     * @mbg.generated
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.end_at
     *
     * @mbg.generated
     */
    private Date endAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_merchant_map.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.id
     *
     * @return the value of factory_merchant_map.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.id
     *
     * @param id the value for factory_merchant_map.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.merchant_id
     *
     * @return the value of factory_merchant_map.merchant_id
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.merchant_id
     *
     * @param merchantId the value for factory_merchant_map.merchant_id
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.factory_id
     *
     * @return the value of factory_merchant_map.factory_id
     * @mbg.generated
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.factory_id
     *
     * @param factoryId the value for factory_merchant_map.factory_id
     * @mbg.generated
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.goods_number
     *
     * @return the value of factory_merchant_map.goods_number
     * @mbg.generated
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.goods_number
     *
     * @param goodsNumber the value for factory_merchant_map.goods_number
     * @mbg.generated
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.trader_number
     *
     * @return the value of factory_merchant_map.trader_number
     * @mbg.generated
     */
    public Integer getTraderNumber() {
        return traderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.trader_number
     *
     * @param traderNumber the value for factory_merchant_map.trader_number
     * @mbg.generated
     */
    public void setTraderNumber(Integer traderNumber) {
        this.traderNumber = traderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.discount_number
     *
     * @return the value of factory_merchant_map.discount_number
     * @mbg.generated
     */
    public Integer getDiscountNumber() {
        return discountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.discount_number
     *
     * @param discountNumber the value for factory_merchant_map.discount_number
     * @mbg.generated
     */
    public void setDiscountNumber(Integer discountNumber) {
        this.discountNumber = discountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.campaign_number
     *
     * @return the value of factory_merchant_map.campaign_number
     * @mbg.generated
     */
    public Integer getCampaignNumber() {
        return campaignNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.campaign_number
     *
     * @param campaignNumber the value for factory_merchant_map.campaign_number
     * @mbg.generated
     */
    public void setCampaignNumber(Integer campaignNumber) {
        this.campaignNumber = campaignNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.start_at
     *
     * @return the value of factory_merchant_map.start_at
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.start_at
     *
     * @param startAt the value for factory_merchant_map.start_at
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.end_at
     *
     * @return the value of factory_merchant_map.end_at
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.end_at
     *
     * @param endAt the value for factory_merchant_map.end_at
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.create_at
     *
     * @return the value of factory_merchant_map.create_at
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.create_at
     *
     * @param createAt the value for factory_merchant_map.create_at
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.update_at
     *
     * @return the value of factory_merchant_map.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.update_at
     *
     * @param updateAt the value for factory_merchant_map.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_merchant_map.valid
     *
     * @return the value of factory_merchant_map.valid
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_merchant_map.valid
     *
     * @param valid the value for factory_merchant_map.valid
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}
