package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class GoodsFactoryMerchantMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.goods_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.factory_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Integer factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.factory_metchat_map_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Integer factoryMetchatMapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.start_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Date startAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.end_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.create_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.update_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_factory_merchant_map.valid
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.id
     *
     * @return the value of goods_factory_merchant_map.id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.id
     *
     * @param id the value for goods_factory_merchant_map.id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.goods_id
     *
     * @return the value of goods_factory_merchant_map.goods_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.goods_id
     *
     * @param goodsId the value for goods_factory_merchant_map.goods_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.factory_id
     *
     * @return the value of goods_factory_merchant_map.factory_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.factory_id
     *
     * @param factoryId the value for goods_factory_merchant_map.factory_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.factory_metchat_map_id
     *
     * @return the value of goods_factory_merchant_map.factory_metchat_map_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Integer getFactoryMetchatMapId() {
        return factoryMetchatMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.factory_metchat_map_id
     *
     * @param factoryMetchatMapId the value for goods_factory_merchant_map.factory_metchat_map_id
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setFactoryMetchatMapId(Integer factoryMetchatMapId) {
        this.factoryMetchatMapId = factoryMetchatMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.start_at
     *
     * @return the value of goods_factory_merchant_map.start_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.start_at
     *
     * @param startAt the value for goods_factory_merchant_map.start_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.end_at
     *
     * @return the value of goods_factory_merchant_map.end_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.end_at
     *
     * @param endAt the value for goods_factory_merchant_map.end_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.create_at
     *
     * @return the value of goods_factory_merchant_map.create_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.create_at
     *
     * @param createAt the value for goods_factory_merchant_map.create_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.update_at
     *
     * @return the value of goods_factory_merchant_map.update_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.update_at
     *
     * @param updateAt the value for goods_factory_merchant_map.update_at
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_factory_merchant_map.valid
     *
     * @return the value of goods_factory_merchant_map.valid
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_factory_merchant_map.valid
     *
     * @param valid the value for goods_factory_merchant_map.valid
     *
     * @mbg.generated Wed Jan 30 23:45:50 CST 2019
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}