package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class MerchantAdminMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.factory_number
     *
     * @mbg.generated
     */
    private Integer factoryNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.start_at
     *
     * @mbg.generated
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.end_at
     *
     * @mbg.generated
     */
    private Date endAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.sign
     *
     * @mbg.generated
     */
    private Byte sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_admin_map.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.id
     *
     * @return the value of merchant_admin_map.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.id
     *
     * @param id the value for merchant_admin_map.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.merchant_id
     *
     * @return the value of merchant_admin_map.merchant_id
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.merchant_id
     *
     * @param merchantId the value for merchant_admin_map.merchant_id
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.admin_id
     *
     * @return the value of merchant_admin_map.admin_id
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.admin_id
     *
     * @param adminId the value for merchant_admin_map.admin_id
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.factory_number
     *
     * @return the value of merchant_admin_map.factory_number
     * @mbg.generated
     */
    public Integer getFactoryNumber() {
        return factoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.factory_number
     *
     * @param factoryNumber the value for merchant_admin_map.factory_number
     * @mbg.generated
     */
    public void setFactoryNumber(Integer factoryNumber) {
        this.factoryNumber = factoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.start_at
     *
     * @return the value of merchant_admin_map.start_at
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.start_at
     *
     * @param startAt the value for merchant_admin_map.start_at
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.end_at
     *
     * @return the value of merchant_admin_map.end_at
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.end_at
     *
     * @param endAt the value for merchant_admin_map.end_at
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.sign
     *
     * @return the value of merchant_admin_map.sign
     * @mbg.generated
     */
    public Byte getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.sign
     *
     * @param sign the value for merchant_admin_map.sign
     * @mbg.generated
     */
    public void setSign(Byte sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.create_at
     *
     * @return the value of merchant_admin_map.create_at
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.create_at
     *
     * @param createAt the value for merchant_admin_map.create_at
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.update_at
     *
     * @return the value of merchant_admin_map.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.update_at
     *
     * @param updateAt the value for merchant_admin_map.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_admin_map.valid
     *
     * @return the value of merchant_admin_map.valid
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_admin_map.valid
     *
     * @param valid the value for merchant_admin_map.valid
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}
