package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class NotificationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.title
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.comment
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.factory_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Integer factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.trader_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Integer traderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.start_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Date startAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.end_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.create_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.update_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_info.valid
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.id
     *
     * @return the value of notification_info.id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.id
     *
     * @param id the value for notification_info.id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.title
     *
     * @return the value of notification_info.title
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.title
     *
     * @param title the value for notification_info.title
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.comment
     *
     * @return the value of notification_info.comment
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.comment
     *
     * @param comment the value for notification_info.comment
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.factory_id
     *
     * @return the value of notification_info.factory_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.factory_id
     *
     * @param factoryId the value for notification_info.factory_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.trader_id
     *
     * @return the value of notification_info.trader_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Integer getTraderId() {
        return traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.trader_id
     *
     * @param traderId the value for notification_info.trader_id
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setTraderId(Integer traderId) {
        this.traderId = traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.start_at
     *
     * @return the value of notification_info.start_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.start_at
     *
     * @param startAt the value for notification_info.start_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.end_at
     *
     * @return the value of notification_info.end_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.end_at
     *
     * @param endAt the value for notification_info.end_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.create_at
     *
     * @return the value of notification_info.create_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.create_at
     *
     * @param createAt the value for notification_info.create_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.update_at
     *
     * @return the value of notification_info.update_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.update_at
     *
     * @param updateAt the value for notification_info.update_at
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_info.valid
     *
     * @return the value of notification_info.valid
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_info.valid
     *
     * @param valid the value for notification_info.valid
     *
     * @mbg.generated Sat Feb 23 00:13:02 CST 2019
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}