package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.trader_factory_merchant_id
     *
     * @mbg.generated
     */
    private Integer traderFactoryMerchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_number
     *
     * @mbg.generated
     */
    private Integer goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.discount_id
     *
     * @mbg.generated
     */
    private Integer discountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.start_at
     *
     * @mbg.generated
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.end_at
     *
     * @mbg.generated
     */
    private Date endAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.factory_confirm_status
     *
     * @mbg.generated
     */
    private Byte factoryConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.factory_confirm_at
     *
     * @mbg.generated
     */
    private Date factoryConfirmAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.factory_confirm_by
     *
     * @mbg.generated
     */
    private Integer factoryConfirmBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_confirm_status
     *
     * @mbg.generated
     */
    private Byte merchantConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_confirm_at
     *
     * @mbg.generated
     */
    private Date merchantConfirmAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_confirm_number
     *
     * @mbg.generated
     */
    private Integer merchantConfirmNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.merchant_confirm_by
     *
     * @mbg.generated
     */
    private Integer merchantConfirmBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.title
     *
     * @return the value of order_info.title
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.title
     *
     * @param title the value for order_info.title
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.comment
     *
     * @return the value of order_info.comment
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.comment
     *
     * @param comment the value for order_info.comment
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.trader_factory_merchant_id
     *
     * @return the value of order_info.trader_factory_merchant_id
     * @mbg.generated
     */
    public Integer getTraderFactoryMerchantId() {
        return traderFactoryMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.trader_factory_merchant_id
     *
     * @param traderFactoryMerchantId the value for order_info.trader_factory_merchant_id
     * @mbg.generated
     */
    public void setTraderFactoryMerchantId(Integer traderFactoryMerchantId) {
        this.traderFactoryMerchantId = traderFactoryMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shop_id
     *
     * @return the value of order_info.shop_id
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shop_id
     *
     * @param shopId the value for order_info.shop_id
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_id
     *
     * @return the value of order_info.goods_id
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_id
     *
     * @param goodsId the value for order_info.goods_id
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_number
     *
     * @return the value of order_info.goods_number
     * @mbg.generated
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_number
     *
     * @param goodsNumber the value for order_info.goods_number
     * @mbg.generated
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount
     *
     * @return the value of order_info.amount
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount
     *
     * @param amount the value for order_info.amount
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.discount_id
     *
     * @return the value of order_info.discount_id
     * @mbg.generated
     */
    public Integer getDiscountId() {
        return discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.discount_id
     *
     * @param discountId the value for order_info.discount_id
     * @mbg.generated
     */
    public void setDiscountId(Integer discountId) {
        this.discountId = discountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.start_at
     *
     * @return the value of order_info.start_at
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.start_at
     *
     * @param startAt the value for order_info.start_at
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.end_at
     *
     * @return the value of order_info.end_at
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.end_at
     *
     * @param endAt the value for order_info.end_at
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_at
     *
     * @return the value of order_info.create_at
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_at
     *
     * @param createAt the value for order_info.create_at
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_at
     *
     * @return the value of order_info.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_at
     *
     * @param updateAt the value for order_info.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.factory_confirm_status
     *
     * @return the value of order_info.factory_confirm_status
     * @mbg.generated
     */
    public Byte getFactoryConfirmStatus() {
        return factoryConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.factory_confirm_status
     *
     * @param factoryConfirmStatus the value for order_info.factory_confirm_status
     * @mbg.generated
     */
    public void setFactoryConfirmStatus(Byte factoryConfirmStatus) {
        this.factoryConfirmStatus = factoryConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.factory_confirm_at
     *
     * @return the value of order_info.factory_confirm_at
     * @mbg.generated
     */
    public Date getFactoryConfirmAt() {
        return factoryConfirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.factory_confirm_at
     *
     * @param factoryConfirmAt the value for order_info.factory_confirm_at
     * @mbg.generated
     */
    public void setFactoryConfirmAt(Date factoryConfirmAt) {
        this.factoryConfirmAt = factoryConfirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.factory_confirm_by
     *
     * @return the value of order_info.factory_confirm_by
     * @mbg.generated
     */
    public Integer getFactoryConfirmBy() {
        return factoryConfirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.factory_confirm_by
     *
     * @param factoryConfirmBy the value for order_info.factory_confirm_by
     * @mbg.generated
     */
    public void setFactoryConfirmBy(Integer factoryConfirmBy) {
        this.factoryConfirmBy = factoryConfirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_confirm_status
     *
     * @return the value of order_info.merchant_confirm_status
     * @mbg.generated
     */
    public Byte getMerchantConfirmStatus() {
        return merchantConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_confirm_status
     *
     * @param merchantConfirmStatus the value for order_info.merchant_confirm_status
     * @mbg.generated
     */
    public void setMerchantConfirmStatus(Byte merchantConfirmStatus) {
        this.merchantConfirmStatus = merchantConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_confirm_at
     *
     * @return the value of order_info.merchant_confirm_at
     * @mbg.generated
     */
    public Date getMerchantConfirmAt() {
        return merchantConfirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_confirm_at
     *
     * @param merchantConfirmAt the value for order_info.merchant_confirm_at
     * @mbg.generated
     */
    public void setMerchantConfirmAt(Date merchantConfirmAt) {
        this.merchantConfirmAt = merchantConfirmAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_confirm_number
     *
     * @return the value of order_info.merchant_confirm_number
     * @mbg.generated
     */
    public Integer getMerchantConfirmNumber() {
        return merchantConfirmNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_confirm_number
     *
     * @param merchantConfirmNumber the value for order_info.merchant_confirm_number
     * @mbg.generated
     */
    public void setMerchantConfirmNumber(Integer merchantConfirmNumber) {
        this.merchantConfirmNumber = merchantConfirmNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.merchant_confirm_by
     *
     * @return the value of order_info.merchant_confirm_by
     * @mbg.generated
     */
    public Integer getMerchantConfirmBy() {
        return merchantConfirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.merchant_confirm_by
     *
     * @param merchantConfirmBy the value for order_info.merchant_confirm_by
     * @mbg.generated
     */
    public void setMerchantConfirmBy(Integer merchantConfirmBy) {
        this.merchantConfirmBy = merchantConfirmBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.valid
     *
     * @return the value of order_info.valid
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.valid
     *
     * @param valid the value for order_info.valid
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}
