package com.srct.service.tanya.common.datalayer.tanya.entity;

import java.util.Date;

public class SalesmanTraderMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.trader_id
     *
     * @mbg.generated
     */
    private Integer traderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.salesman_id
     *
     * @mbg.generated
     */
    private Integer salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.start_at
     *
     * @mbg.generated
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.end_at
     *
     * @mbg.generated
     */
    private Date endAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesman_trader_map.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.id
     *
     * @return the value of salesman_trader_map.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.id
     *
     * @param id the value for salesman_trader_map.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.trader_id
     *
     * @return the value of salesman_trader_map.trader_id
     * @mbg.generated
     */
    public Integer getTraderId() {
        return traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.trader_id
     *
     * @param traderId the value for salesman_trader_map.trader_id
     * @mbg.generated
     */
    public void setTraderId(Integer traderId) {
        this.traderId = traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.salesman_id
     *
     * @return the value of salesman_trader_map.salesman_id
     * @mbg.generated
     */
    public Integer getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.salesman_id
     *
     * @param salesmanId the value for salesman_trader_map.salesman_id
     * @mbg.generated
     */
    public void setSalesmanId(Integer salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.start_at
     *
     * @return the value of salesman_trader_map.start_at
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.start_at
     *
     * @param startAt the value for salesman_trader_map.start_at
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.end_at
     *
     * @return the value of salesman_trader_map.end_at
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.end_at
     *
     * @param endAt the value for salesman_trader_map.end_at
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.create_at
     *
     * @return the value of salesman_trader_map.create_at
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.create_at
     *
     * @param createAt the value for salesman_trader_map.create_at
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.update_at
     *
     * @return the value of salesman_trader_map.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.update_at
     *
     * @param updateAt the value for salesman_trader_map.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesman_trader_map.valid
     *
     * @return the value of salesman_trader_map.valid
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesman_trader_map.valid
     *
     * @param valid the value for salesman_trader_map.valid
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}
